apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      app: db-deployment
  template:
    metadata:
      labels:
        app: db-deployment
    spec:
      containers:
      - name: db-deployment
        image: postgres:15-alpine
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql/data
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
        ports:
        - containerPort: 5432
      volumes:
        - name: db-data
          emptyDir: {}
