apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deploy
  labels:
    app: result
spec:
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: roxsross12/result:TAG
        ports:
        - containerPort: 80